name: Project Generator

on:
  push:
    branches: [ main ]

jobs:
  generator:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Installing Deps'
        run: npm i -g pnpm && pnpm i
      - name: 'Generate Project'
        run: node app-builder.js
      - name: Commit and push project
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "[bot,builder]: ran builder;" || echo "No changes to commit"
            git push